AWSTemplateFormatVersion: '2010-09-09'
Description: VPC con dos subredes públicas para Ponchoneta
Resources:
  PonchonetaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: PonchonetaVPC

  PonchonetaInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: PonchonetaIGW

  PonchonetaVPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref PonchonetaVPC
      InternetGatewayId: !Ref PonchonetaInternetGateway

  PonchonetaPublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PonchonetaVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PonchonetaPublicSubnet1

  PonchonetaPublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PonchonetaVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: PonchonetaPublicSubnet2

  PonchonetaPublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref PonchonetaVPC
      Tags:
        - Key: Name
          Value: PonchonetaPublicRouteTable

  PonchonetaPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: PonchonetaVPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PonchonetaPublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref PonchonetaInternetGateway

  PonchonetaSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PonchonetaPublicSubnet1
      RouteTableId: !Ref PonchonetaPublicRouteTable

  PonchonetaSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PonchonetaPublicSubnet2
      RouteTableId: !Ref PonchonetaPublicRouteTable

Outputs:
  PonchonetaPublicSubnet1:
    Description: Subnet pública 1
    Value: !Ref PonchonetaPublicSubnet1
    Export:
      Name: PonchonetaPublicSubnet1

  PonchonetaPublicSubnet2:
    Description: Subnet pública 2
    Value: !Ref PonchonetaPublicSubnet2
    Export:
      Name: PonchonetaPublicSubnet2

  PonchonetaVPC:
    Description: VPC principal
    Value: !Ref PonchonetaVPC
    Export:
      Name: PonchonetaVPC